site_name: Gixy docs
site_description: "Automatic documentation from sources, for Gixy."
site_url: https://gixy.getpagespeed.com/
repo_url: https://github.com/dvershinin/gixy
theme:
  name: "material"
  palette:
    scheme: slate
    primary: teal
    accent: purple
  features:
    - navigation.expand
plugins:
  - search
nav:
  - Overview: index.md
  - Plugins:
    - Server Side Request Forgery: en/plugins/ssrf.md
    - HTTP Splitting: en/plugins/httpsplitting.md
    - Problems with referrer/origin validation: en/plugins/origins.md
    - Redefining of response headers by "add_header" directive: en/plugins/addheaderredefinition.md
    - Request's Host header forgery: en/plugins/hostspoofing.md
    - none in valid_referers: en/plugins/validreferers.md
    - Multiline response headers: en/plugins/addheadermultiline.md
    - Path traversal via misconfigured alias: en/plugins/aliastraversal.md
    - If is evil when used in location context: en/plugins/if_is_evil.md
    - Allow specified without deny: en/plugins/allow_without_deny.md
    - Setting Content-Type via add_header: en/plugins/add_header_content_type.md
    - Using external DNS nameservers: https://blog.zorinaq.com/nginx-resolver-vulns/
    - Version Disclosure: en/plugins/version_disclosure.md
  - 'Blog': 'https://www.getpagespeed.com/posts'
markdown_extensions:
  - admonition
  - markdown_include.include
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: "Â¤"
extra:
  generator: false
